server {
    listen 80;

    # Serve React app
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Quan trọng cho React Router
    }

    # Proxy API sang Spring Boot
    location /api/ {
        proxy_pass http://spring-app:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}